---
kind: pipeline
type: kubernetes

# resource requests are defined on the pipeline level
resources:
  request:
    cpu: 500
    memory: 250MiB

steps:
  - name: en
    image: alpine
    commands:
      - echo hello
