---
kind: pipeline
type: kubernetes
name: ss14


# resource requests are defined on the pipeline level
resources:
  request:
    cpu: 500
    memory: 250MiB

platform:
  os: linux
  arch: amd64

steps:
- name: publish
  image: plugins/docker
  settings:
    dockerfile: ss14/Dockerfile
    repo: eldios/ss14-server
    auto_tag: "true"
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
  tags:
    - latest
    - '0.0.1'

trigger:
  branch: [ master ]
  event:  [ push, tag ]
